version: '3.1'

services:
  portfolio:
    build: .
    container_name: backend
    command: uvicorn main:app --reload --host=0.0.0.0 --port=11111
    volumes:
    - ./backend:/backend
    restart: on-failure
    networks:
      - default
    ports:
      - "11111:11111"

volumes:
  backend: